### ISSUE TITLE
Doesn't work with big collections: DEADLINE_EXCEEDED: Deadline Exceeded

### ISSUE THREAD

**Issue by robertkeus** [dalenguyen/firestore-import-export#11]
When I want to export a big collection
Then I get this error: DEADLINE_EXCEEDED: Deadline Exceeded

**Comment by dalenguyen** [comment]
Hi @robertkeus, how does your data structure looks like and how big it is? Did it import anything?

**Comment by robertkeus** [comment]
@dalenguyen it's a huge file and big backup. I needed to export the data.

**Comment by dalenguyen** [comment]
Hi @robertkeus, check your current account, if it exceeds the quotas:

https://firebase.google.com/docs/firestore/quotas

**Comment by philliphartin** [comment]
@robertkeus - Did you ever resolve your issue? I'm up against the same thing and have tried numerous ways to address it using node
