### ISSUE TITLE
How to import to Firestore With An Auto ID

### ISSUE THREAD

**Issue by artistic** [dalenguyen/firestore-import-export#13]
Hie Im still a newbie to Firestore. I have the import working when i enter a manual ID like : 
{
	"menu" : {

		"1" : {
			"menu_item" : "Menu 1",
		},
		"2" : {
			"menu_item" : "Menu 2",
		}
}
}

but i would like to let Firestore auto generate the ID 
Please help. Thank you in advance

**Comment by dalenguyen** [comment]
Hi @artistic, you can try this guide and run a loop to create a document without an ID.

https://github.com/dalenguyen/firebase-functions-helper/blob/master/docs/firestore.md#5-create-a-new-document-without-an-id
