### ISSUE TITLE
Exported Json File on One Line

### ISSUE THREAD

**Issue by Harin329** [dalenguyen/firestore-import-export#17]
I have two test documents in a collection right now and all the information is exported, but it's all in one line. Is there anything I need to add to get it to format nicely like the example json file without having to manually do it by entering.

**Comment by dalenguyen** [comment]
Hi @Harin329, can you take a snapshot of your results? Thanks,

**Comment by Harin329** [comment]
This is the sample code. It's all under one line, I could use an online formatter, but was wondering if there was any even simpler code additions to get it looking nice!

`{"Canada":{"Motomachi Shokudo":{"Menu":{"Appetizers":{"Chicken Chashu Rice":{"Raters":1,"Price":6,"Rating":2.5}}},"Rating":2.5,"Website":"www.google.com","Location":{"_latitude":49.290683,"_longitude":-123.133956},"Phone":"(604) 999-9999","NumRates":1,"Country":"Canada","City":"Vancouver"}}}`

**Comment by dalenguyen** [comment]
Hi @Harin329. for this, you can quickly use an IDE plugin to format the JSON file. 

This is an example if you use VSCode: https://stackoverflow.com/questions/29973357/how-do-you-format-code-in-visual-studio-code-vscode
