### ISSUE TITLE
Sub Collection Cannot be retrieved

### ISSUE THREAD

**Issue by thehuangkai** [dalenguyen/firestore-import-export#19]
Hi,

Appreciate your work. However I am having some issues with getting the sub collections using both the npm package as well as the git hub repo.

My database is something like:

shops_collection
  -document_1
       -menu_collection
  -document 2
       -menu_collection

so i tried to input "shops_collection" then "menu_collection"

like node exportjs shops_collection menu_collection but it returns an empty list. But node exportjs shops_collection works.

Also if I do not input variables and just .backup([]), the root collections are returned but not the subcollections.

Maybe you can help me take a look with that? Thanks

**Comment by otnielgomez** [comment]
Any answer? I have the same problem.

**Comment by dalenguyen** [comment]
Hi @thehuangkai @otnielgomez sorry for the late reply. Have you tried this one? https://www.npmjs.com/package/firestore-export-import
