### ISSUE TITLE
Auto generate firestore document ID

### ISSUE THREAD

**Issue by nebitrams** [dalenguyen/firestore-import-export#22]
@dalenguyen Thanks for contributing this library for data import.  I managed to use it to upload my data.

```
{
  "collectionName" : {
    "ID00001" : {
      "venue" : "Super Ring"
    }
  }
}
```

It would be to be able to automatic generate the key because I am uploading new data.  At the moment, I am trying to generate the ID outside this import utility.

**Comment by dalenguyen** [comment]
Hi @nebitrams. You can check out this package for auto generating document ID. https://github.com/dalenguyen/firebase-functions-helper/blob/master/docs/firestore.md
