### ISSUE TITLE
Timestamps not being properly handled?

### ISSUE THREAD

**Issue by waylandc** [dalenguyen/firestore-import-export#23]
My original database uses Firestore's timestamp type.

The export script creates:
`"endDate": { "_seconds": 1577318400, "_nanoseconds": 0 }`

Then if I import, the newly imported DB no longer has the timestamp field, instead it has a map with the above structure.

**Comment by dalenguyen** [comment]
Hi @waylandc, this is already fixed. You need to add "endDate" to the parameter in order to import date type.
