### ISSUE TITLE
the function will terminate if one of the subcollection is empty

### ISSUE THREAD

**Issue by chow2324** [dalenguyen/firestore-import-export#25]
I am trying to export the firestore database with subcollection,
but the program will terminate if one of the subcollection is empty.

For example, my database structure is like : users/<KEY>/userinfo

but some users didn't have a userinfo yet, and the function will end at this point

is there anyway to solve it?

**Comment by dalenguyen** [comment]
Hi @michealchow, please try this package: https://github.com/dalenguyen/firestore-backup-restore
