### ISSUE TITLE
How to import Firestore Collection's Documents with List of Map having Timestamp fields?

### ISSUE THREAD

**Issue by Subroid** [dalenguyen/firestore-import-export#29]
I'm trying this command obviously as guessing : 
`node import.js firestore-export.json date=FoodGrains[0].product_adding_timestamp` 
^What I'm trying above is I have a List of Product objects as Maps in one Firestore Document and all these objects have two Timestamp fields "product_adding_timestamp" and "product_updating_timestamp". Trying the above-guessed command giving me this error : 
![image](https://user-images.githubusercontent.com/29721105/67073062-db235580-f1a3-11e9-9521-b48d91ac4e4b.png)
Here's the screenshot of FoodGrains collection : 
![image](https://user-images.githubusercontent.com/29721105/67073176-1887e300-f1a4-11e9-8068-ab6a6d6a2c3a.png)
Here's the screenshot of fields every List object contains : 
![image](https://user-images.githubusercontent.com/29721105/67073293-6997d700-f1a4-11e9-9efc-50118fc3e585.png)
^I want to import product_adding_timestamp field values as Timestamp object, not as Map of _nanoseconds and _seonds keys.
Sorry. Because of not being a native English speaker I could not make this question brief.

**Comment by Subroid** [comment]
bump

**Comment by dalenguyen** [comment]
Hi @subrud, please the NPM package of this one. It solves the issue of timestamp. 

https://github.com/dalenguyen/firestore-backup-restore
