### ISSUE TITLE
Import customers, workers and categories to firestore

### ISSUE THREAD

**Issue by LouBNielsen** [dalenguyen/firestore-import-export#32]
Related to https://github.com/prolike/dillydally/issues/107

**Comment by dalenguyen** [comment]
@LouBNielsen  I couldn't see the prolike's issue.

**Comment by LouBNielsen** [comment]
Hi @dalenguyen
My mistake! I was ment to open this issue in my own repository, not here.
Closing issue.

**Comment by LouBNielsen** [comment]
Issue moved to [prolike/dillydally #124](https://github.com/prolike/dillydally/issues/124) via [**ZenHub**](https://www.zenhub.com/)
