### ISSUE TITLE
Is it possible? [InitializeApp] without 'databaseURL'

### ISSUE THREAD

**Issue by ybhwang** [dalenguyen/firestore-import-export#33]
I just tried with importing `serviceAccountKey.json` for usage, and I didn't changed value of  `databaseURL`at `InitializeApp`.
1. It works fine, it it possible?
2. In the case of me, is it possible to submit my datas to your `databaseUrl: "https://ionic-firestore-dn.firebaseio.com"`?

**Comment by dalenguyen** [comment]
It's not possible to submit your data to that databaseUrl. You will more than just a URL. Please replace it with your own.
