### ISSUE TITLE
invalid authentication credentials.

### ISSUE THREAD

**Issue by umer7** [dalenguyen/firestore-import-export#5]
i am getting this error

>  { Error: 16 UNAUTHENTICATED: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential.

**Comment by dalenguyen** [comment]
Hi @umer7 , please describe the steps that you take and take a snapshot if it is possible.

**Comment by umer7** [comment]
I followed all steps that you describe but  i stuck at this error . Are there any prerequisite steps i need(i have previously deployed firebase functions  ) Thanks in Advance
![err11](https://user-images.githubusercontent.com/24353882/43076817-48e2e0e6-8e3a-11e8-8c43-28bc03a63ddc.PNG)

**Comment by dalenguyen** [comment]
Hi @umer7 , did you download your **serviceAccountKey.json** file from firebase and change your databaseURL? 

[](// You should replace databaseURL with your own
admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  databaseURL: "**https://your-databaseURL.firebaseio.com**"
});)

**Comment by umer7** [comment]
yes i have done both things...still getting this

**Comment by umer7** [comment]
i have done both thing still have this error

**Comment by dalenguyen** [comment]
@umer7 not sure what happens. Could you please give this one a try? 

https://github.com/dalenguyen/firestore-backup-restore

**Comment by umer7** [comment]
Currently I am using Free Plan of Fire-base ...does it has any thing to do with that ?

**Comment by dalenguyen** [comment]
@umer7 It shouldn't have anything to do with that. Did the second method work?

**Comment by birchb** [comment]
I had a similar error response. I figured out that I had changed a parameter on my database, perhaps the public facing name or something.

Generating a new service key solved the problem.

**Comment by dalenguyen** [comment]
Hi @birchb , I'm glad that there are some methods to fix this :)
