### ISSUE TITLE
Dates are not supported

### ISSUE THREAD

**Issue by uknowmeright** [dalenguyen/firestore-import-export#6]
Everything worked correctly for me except the export of dates.
They seem to be imported back into the database as a string.

ex:
2018-05-31T04:00:00.000Z

Any advice on getting around this?

Thanks,

**Comment by dalenguyen** [comment]
Hi @uknowmeright , in this case, I think that you can loop through the array and convert the string to date by using a helper like the [moment package](https://www.npmjs.com/package/moment) or **new Date()** in JavaScript, then write data to firestore. You can use [Firebase function helper](https://github.com/dalenguyen/firebase-functions-helper/blob/master/docs/firestore.md#4-create-a-document-with-id-in-firestore) to do it.
