### ISSUE TITLE
Dates

### ISSUE THREAD

**Issue by jprentissone** [dalenguyen/firestore-import-export#8]
Hello,

What format can I use to ensure that my dates are imported as either timestamp or date.  It is importing them as strings or objects.

**Comment by dalenguyen** [comment]
Hi @jprentissone, I will take a look at this issue. Meanwhile, you can modify the code with **new Date()** if you have date value in your data before importing to firestore.

**Comment by jprentissone** [comment]
Thank you so much!!

Appreciate it.

**Comment by dalenguyen** [comment]
Hi @jprentissone , I add the date support to Firestore. Please read the instruction in the readme.md file. Please let me know if you have any issue. Thanks,

**Comment by jprentissone** [comment]
Fantastic. Thanks so much for the follow up.

**Comment by dalenguyen** [comment]
@jprentissone you're welcome. I just added some validations. Please let me know if it works.
