### ISSUE TITLE
References Support

### ISSUE THREAD

**Issue by mfferreira** [dalenguyen/firestore-import-export#9]
Thank you for the tool. Really useful!

Reading through the exported that, it seems to get everything right about the reference paths.
But when I try to import the same json, the references are just set as objects.

Is there any special way to arrange the data to be able to set that data as an actual reference?

Cheers

**Comment by dalenguyen** [comment]
Hi @mfferreira, I haven't written the function to import all yet, for now, you have to edit and import them separately like the sample JSON for a single collection. I will update the feature later.
